### ISSUE TITLE
Are you kidding me?

### ISSUE THREAD

**Issue by devlato** [vkhv/is-js-extension#1]
Do you really need a separate node package to check if file extension is '.js'?

**Comment by vkhv** [comment]
Why not? i think it is convenient -  store all common functions in small modules.

**Comment by devlato** [comment]
@vkhv Because it's fucking stupid maybe? 

P. S. https://habrahabr.ru/post/280099/

**Comment by vkhv** [comment]
i see, still love your bicycle  and good luck.

**Comment by devlato** [comment]
@vkhv Pffffff, so stupid
